apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: labkube
  name: labkube
spec:
  replicas: 2
  selector:
    matchLabels:
      run: labkube
  template:
    metadata:
      labels:
        run: labkube
    spec:
      containers:
      - image: dbenque/labkube:v1
        env:
        - name: MY_LABKUBE_VAR
          value: "Hello from the environment"
        name: labkube
        ports:
        - containerPort: 8080      